services:
  - name: voting-backend
    build:
      context: .
    env:
      DJANGO_SETTINGS_MODULE: your_project.settings
      DEBUG: 'False'
      ALLOWED_HOSTS: 'your-domain.com'
    deploy:
      startCommand: "gunicorn your_project.wsgi"
