# Generated by Django 5.0.4 on 2024-05-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.CharField(max_length=50, unique=True)),
                ('voter_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('aadhaar_number', models.CharField(max_length=12, unique=True)),
            ],
        ),
    ]
